### ISSUE TITLE
Bloodhound crashes after admin password reset

### ISSUE THREAD

**Issue by Techbrunch** [badsectorlabs/ludus_bloodhound_ce#1]
I might be missing something but when using this role bloodhound crashed after resetting the admin password:

```
{"level":"info","time":"2024-09-18T13:44:42.480634145Z","message":"Reading configuration found at /bloodhound.config.json"}
{"level":"warn","time":"2024-09-18T13:44:42.483099586Z","message":"unable to find a configuration element by path: disable_cypher_qc"}
{"level":"info","time":"2024-09-18T13:44:42.483490543Z","message":"Logging configured"}
{"level":"error","time":"2024-09-18T13:44:42.490411391Z","message":"failed to initialize database, got error failed to connect to `host=app-db user=bloodhound database=bloodhound`: dial error (dial tcp 172.18.0.3:5432: connect: connection refused)"}
{"level":"fatal","time":"2024-09-18T13:44:42.490444946Z","message":"Failed starting the server: failed to connect to databases: error while attempting to create database connection: failed to connect to `host=app-db user=bloodhound database=bloodhound`: dial error (dial tcp 172.18.0.3:5432: connect: connection refused)"}
```

It looks like it's because this line is commented in `docker-compose.yml`:

```
version: '3'
services:
  app-db:
    image: docker.io/library/postgres:13.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-bloodhound}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-bloodhoundcommunityedition}
      - POSTGRES_DB=${POSTGRES_DB:-bloodhound}
    # Database ports are disabled by default. Please change your database password to something secure before uncommenting
    # ports:
   #   - 127.0.0.1:${POSTGRES_PORT:-5432}:5432
```

Uncommenting the line fixes the issue:

```
docker compose up -d
```
